[build-system]
requires = ["setuptools>=68", "wheel", "pybind11>=2.10"]
build-backend = "setuptools.build_meta"

[project]
name = "optionpricer"
version = "0.1.0"
description = "C++ pricers via pybind11"
requires-python = ">=3.9"
